// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPsuA2aY0pAUCHbESz1gLSs5F_7i4dfOk',
    appId: '1:416102166155:android:e714617729a062aa3dee8e',
    messagingSenderId: '416102166155',
    projectId: 'storyteller-450807',
    storageBucket: 'storyteller-450807.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASCSOf2YvPq_nt_Nyjf0b2pFakmqXVQR4',
    appId: '1:416102166155:ios:71a6d1cf00acaa373dee8e',
    messagingSenderId: '416102166155',
    projectId: 'storyteller-450807',
    storageBucket: 'storyteller-450807.firebasestorage.app',
    androidClientId: '416102166155-2ncg39pfonu4jtjq5443vu4sp82nfu5f.apps.googleusercontent.com',
    iosClientId: '416102166155-7l4e28v989gh40nguahlk32objen1qqo.apps.googleusercontent.com',
    iosBundleId: 'com.example.jokes',
  );

}